const height = 1000;
const width = 1000;
const svg = d3.select('div').append('svg').attr("height", height).attr("width", width);
const dataSet = [[1, 2], [3, 4], [7, 8]];
const padding = 50;
const xScale = d3.scaleLinear().domain([0, d3.max(dataSet, (d) => d[0])]).range([padding, width - padding]);
const yScale = d3.scaleLinear().domain([0, d3.max(dataSet, (d) => d[0])]).range([height - padding, padding]);
const xAxis = d3.axisBottom(xScale);
const yAxis = d3.axisLeft(yScale);
svg.append("g").attr("transform", "translate(0," + (height - padding) + ")").attr("id", "x-axis").call(xAxis);
svg.append("g").attr("transform", "translate(" + (padding) + ",0)").attr("id", "y-axis").call(yAxis);